

class Brackets3{
	
	
	synchronized static public void generate(String threadCode) {
		for(int i =1; i<=10; i++) {
			
			if(i<=5) {
				System.out.print("[");
			}else {
				System.out.print("]");
			}
		}
		System.out.println("Generated by thread : - " + threadCode);
	}
	
	
}


public class StaticSynchronization {

	public static void main(String[] args) {
		
		//Brackets brackets = new Brackets();	no need to make object now
		
		new Thread(new Runnable() {
			
			@Override
			public void run() {
				for(int i =1; i<=5; i++) {
					//when static is used directly call the class with method using dot
					Brackets3.generate("Thread 1");
				}	
			}
		}).start();
		
		new Thread(new Runnable() {
			
			@Override
			public void run() {
				for(int i =1; i<=5; i++) {
					Brackets3.generate("Thread 2");
				}	
			}
		}).start();

	}

}
